### PR TITLE
Initialize CI

### PR DESCRIPTION
**Pull request by plzfday**
## What is this feature?

Setup CI file for GitHub Actions. Initially it was based on bun, but due to its instability with Next JS, it was changed to Yarn, a better toolkit for dependency management than npm.

## Task Details

- [x] Add `ci.yaml` file for GitHub actions. This runs unit tests.
- [x] Add a sample unit test code that should be removed when merging other PRs.

## Reference Materials (Optional)

### CODE REVIEW

**Review by utilForever — COMMENTED** [review]
Did you changed toolkit from bun to yarn?
It would be nice to have a description of why you made the change.

**Comment by plzfday** [comment]
> Did you changed toolkit from bun to yarn? It would be nice to have a description of why you made the change.

I have made a change in the description. Could you check it again, please?

**Review by utilForever — APPROVED** [review]
LGTM now. Thanks for your work! 🎉
p.s. The reason why we need to add `yarn.lock` is its dependency?

**Comment by plzfday** [comment]
Yes, exactly. AFAIK, we can keep the same version of dependencies in each of our local computers with the `.lock` file.

**Comment by utilForever** [comment]
> Yes, exactly. AFAIK, we can keep the same version of dependencies in each of our local computers with the `.lock` file.

Okay. I understand. Thanks~

**Pull request merged**
