### PR TITLE
Create registration page

### LINKED ISSUE #5: Create Registration page
image

### PR DESCRIPTION
**Pull request by plzfday**
Resolves #5 

The changes are:
- New register page
- Terms and Conditions modal
- Also considered mobile view

image
image

### CODE REVIEW

**Review by utilForever — COMMENTED** [review]
Can you write some unit tests for email validation, password check and so on?

**Comment by plzfday** [comment]
There's no validation process at the moment. Do you think this PR includes it? I suggest adding that later when we connect with the backend.

**Comment by utilForever** [comment]
> There's no validation process at the moment. Do you think this PR includes it? I suggest adding that later when we connect with the backend.

I think that some tests such as email validation and password check can be tested with client-side. I'm not sure why you need the backend to do these tests.

**Review by utilForever — APPROVED** [review]
Through the discussion, we decided to work on the test code in another PR.

**Pull request merged**
